version: "3"

services:
  graphql-api:
    container_name: "api-gateway"
    restart: "always"
    build:
      context: ./graphqlapi
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./graphqlapi:/usr/src/app

  auth-service:
    container_name: "auth-service"
    restart: "always"
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3001:3000"
    volumes:
      - ./auth-service:/usr/src/app

  vehicle-service:
    container_name: "vehicle-service"
    restart: "always"
    build:
      context: ./vehicle-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3002:3000"
    volumes:
      - ./vehicle-service:/usr/src/app

  email-service:
    container_name: "email-service"
    restart: "always"
    build:
      context: ./email-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3003:3000"
    volumes:
      - ./email-service:/usr/src/app

  core-service:
    container_name: "core-service"
    restart: "always"
    build:
      context: ./core-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3004:3000"
    volumes:
      - ./core-service:/usr/src/app

  redis-parka-microservices:
    container_name: "redis-parka-microservices"
    restart: "always"
    image: redis
    ports:
      - "6379:6379"
