version: "3"

services:
  graphql-api:
    container_name: "api-gateway"
    restart: "always"
    build:
      context: ./graphqlapi
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3000:3000"
  auth-service:
    container_name: "auth-service"
    restart: "always"
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3001:3000"
  redis:
    container_name: "redis"
    restart: "always"
    image: redis
    ports:
      - "6379:6379"
