version: "3"

services:
  graphql-api:
    container_name: "graphql-gateway"
    restart: "always"
    build:
      context: ./graphqlapi
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./graphqlapi:/usr/src/app

  auth-service:
    container_name: "auth-service"
    restart: "always"
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3001:3000"
    volumes:
      - ./auth-service:/usr/src/app

  vehicle-service:
    container_name: "vehicle-service"
    restart: "always"
    build:
      context: ./vehicle-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3002:3000"
    volumes:
      - ./vehicle-service:/usr/src/app

  email-service:
    container_name: "email-service"
    restart: "always"
    build:
      context: ./email-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3003:3000"
    volumes:
      - ./email-service:/usr/src/app

  core-service:
    container_name: "core-service"
    restart: "always"
    build:
      context: ./core-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3004:3000"
    volumes:
      - ./core-service:/usr/src/app

  redis-parka-microservices:
    container_name: "redis-parka-microservices"
    restart: "always"
    image: redis
    ports:
      - "6379:6379"

  payment-service:
    container_name: "payment-service"
    restart: "always"
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3005:3000"
    volumes:
      - ./payment-service:/usr/src/app

  review-service:
    container_name: "review-service"
    restart: "always"
    build:
      context: ./review-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3006:3000"
    volumes:
      - ./review-service:/usr/src/app

  parking-service:
    container_name: "parking-service"
    restart: "always"
    build:
      context: ./parking-service
      dockerfile: Dockerfile
    external_links:
      - redis
    ports:
      - "3007:3000"
    volumes:
      - ./parking-service:/usr/src/app

  nginx-parka-microservices-proxy-server:
    container_name: "nginx-parka-microservices-proxy-server"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: "always"
    depends_on:
      - graphql-api
      - auth-service
      - vehicle-service
      - email-service
      - core-service
      - payment-service
      - parking-service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/cert:/etc/nginx/certs
